### ISSUE TITLE
显示多个悬浮框

### ISSUE THREAD

**Issue by andavid** [ZhuoKeTeam/QPM#1]
应用从启动到首页经过了多个 Activity，在首页的时候显示了多个悬浮框，关闭的时候只能关闭最近的一个悬浮框，其他悬浮框只有强制停止应用才能关掉。

**Comment by gdky005** [comment]
该问题是多进程造成的，可以这样解决：
在主App 的Application 中

if (ProcessUtils.isMainProcess()) {
            QPMManager.getInstance().init(this);
            QPMManager.getInstance().floatViewShow();
}
