### ISSUE TITLE
初步体验后发现的问题和建议清单： （清单见内文）

### ISSUE THREAD

**Issue by yangyiRunning** [ZhuoKeTeam/QPM#4]
问题：

1.  Activity堆栈信息有延迟，经常Activity都点了返回键了，上一波的Activity堆栈信息才显示出来。

2. 如果想看尽可能多的信息，在“悬浮窗模块展示开关”中开启尽可能多的信息展示后，App会有严重的掉帧现象。最恐怖时会掉到个位数。关掉一些悬浮窗展示后即正常。

3. API向下只兼容到19，App如果想集成必须手动修改minSDK才可用。

4. 网络接口API列表，点击App应用后没有抓取到相应的报文，用的network request框架是Okgo。

建议：

除以上问题外，建议：

1. 手机信息基本面板和功能清单信息基本面板目前看来，貌似没有发现手动复制的功能。比如我想复制UA、ip地址之类的，只能干看着。

2. 建议在面板外部提供展开和收起按钮，每次展开和收起都要点Android小人进入QRM内部去设置很麻烦。

以上。

**Comment by gdky005** [comment]
非常感谢你意见，我们会尽快做出对应修改。

我们的后台检测基本是每隔1秒检测一次，后期可以考虑把这个时间降低。

**Comment by akvsdk** [comment]
希望能把minSDK 换到16
