### ISSUE TITLE
android o CPU

### ISSUE THREAD

**Issue by wcglws** [ZhuoKeTeam/QPM#6]
totalCPU在8.0以上的手机取不到，楼主采取什么方案解决的？

**Comment by wcglws** [comment]
![image](https://user-images.githubusercontent.com/16982083/50723407-4d94de80-1118-11e9-9b89-6f761236ded0.png)
就没变化，一直是0%

**Comment by wcglws** [comment]
你手机是否root 或者刷了开发版的系统？

**Comment by gdky005** [comment]
是开发版本的，我找一个稳定版本试试看。

**Comment by wcglws** [comment]
不对。。我有个小米MIX2开发版MIUI10 9.1.2  CPU也一直是0%哎。。最近我们公司的APM项目易购反馈CPU猜不到的问题，我查了好多资料，看了好多开源的APM项目，没有什么可行的方案，你这个方案很新颖，想交流下

**Comment by 18811727185** [comment]
android cpu要么从文件获取，要么从top获取，有的机型获取有问题，暂时也没找到好的方法，studio的profiler也不知道怎么获取的
